# [Info]
site_name: faii-book
site_url: https://faiimea.github.io
site_author: faii
site_description: faii-book

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default 
      primary: indigo 
      accent: orange 
      toggle:
        icon: material/weather-night 
        name: 切换至夜间模式 
    - scheme: slate 
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs 
    - navigation.top 
    - navigation.indexes 
    - navigation.expand 
    - search.suggest 
    - search.highlight 
  language: zh 
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs 
## [top-right corner]
repo_url: https://github.com/faiimea 
repo_name: faii.github 
## [bottom-left corner]
copyright: Copyright &copy; 2022 faii 
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/317064082
      name: Bilibili | falii- 
    - icon: fontawesome/brands/github
      link: https://github.com/faiimea
      name: GitHub | faiimea

# [Navigtion]
nav:
- 关于:
    - ABOUT/index.md 
    - 更新日志: ABOUT/date.md
- ACG:
    - Life/index.md
    - 虚拟主播: 
        - Vtubers: Life/vtubers/vtuber.md
        - 绊爱:  Life/vtubers/kizuno.md
        - 戌亥床:  Life/vtubers/inui.md
    - 动漫: 
        - animes: Life/animes/anime.md
        - Grandblue: Life/animes/Grandblue.md
    - 角色: Life/character.md
    - gal: 
        - gals: Life/gals/gal.md
    - game: Life/game.md
- Fun:
    - Chase/index.md
    - 音乐: 
        - music: Chase/musics/music.md
    - 探索: 
        - world: Chase/more/explore.md
    - 故事: 
        - stories : Chase/stories/story.md
    - 哲学: 
        - 哲学？: Chase/philos/philo.md
    - 社会: 
        - 社会? : Chase/socies/socie.md
    - 旅行: 
        - 游记: Chase/travels/travel.md
        - 杭州: Chase/travels/hangzhou.md    
- 专业:
    - Step/index.md   
    - 网站: Step/web.md
    - 书籍: 
        - 书: Step/books/book.md
        - 《1Q84》: Step/books/《1Q84》.md
        - 《1984》: Step/books/《1984》.md
        - 《海边的卡夫卡》: Step/books/《海边的卡夫卡》.md
        - 《荒原狼》: Step/books/《荒原狼》.md
        - 《菊与刀》: Step/books/《菊与刀》.md
        - 《美丽新世界》: Step/books/《美丽新世界》.md
        - 《挪威的森林》: Step/books/《挪威的森林》.md
        - 《奇鸟形状录》: Step/books/《奇鸟形状录》.md
        - 《史蒂夫·乔布斯传》: Step/books/《史蒂夫·乔布斯传》.md
        - 《西线无战事》: Step/books/《西线无战事》.md
        - 《悉尼》: Step/books/《悉尼》.md
        - 《政治经济学概论》: Step/books/《政治经济学概论》.md
        - 《Economics Lecture Notes》: Step/books/《Economics Lecture Notes》.md
        - 《Excellent Sheep》: Step/books/《Excellent Sheep》.md
        - 《Practice of Philosophy》: Step/books/《Practice of Philosophy》.md
    - 项目: 
        - 项目line: Step/projects/project.md
        - 项目map: Step/projects/M.A.P.md

- Blog:
    - blog/index.md
    - lc:
      - leetcode: blog/lc/leetcode.md
    - HUJI-NTT:
      - 汇编器(cpp): blog/NandtoTeris/assembly.md
      - VS编译器: blog/NandtoTeris/VS_trans.md
      - Chapter 1 Boolean logic: blog/NandtoTeris/c1.md
      - Chapter 2 Boolean Arithmetic: blog/NandtoTeris/c2.md
      - Chapter 3 Sequential Logic: blog/NandtoTeris/c3.md
      - Chapter 4 Machine Languaged: blog/NandtoTeris/c4.md
      - Chapter 5 Computer Architecture: blog/NandtoTeris/c5.md
      - Chapter 6 Assembler: blog/NandtoTeris/c6.md
      - Chapter 7 Virtual Machine I Stack Arithmetic: blog/NandtoTeris/c7.md
      - Chapter 8 Virtual Machine II Program Control: blog/NandtoTeris/c8.md
    - UCB-CS61A:
        - note 1: blog/CS61A/lec1.md
        - note 2: blog/CS61A/lecture2.md
        - note 3: blog/CS61A/lec3.md
        - note 4: blog/CS61A/lec4.md
        - note 5: blog/CS61A/lec5.md
        - note 6: blog/CS61A/l6.md
        - note 7: blog/CS61A/2-1.md
        - note 8: blog/CS61A/2-2.md
        - note 9: blog/CS61A/2-3.md
    - HAR-CS50:
        - C语言: blog/CS50/C.md
        - 网页开发: blog/CS50/Web.md
        - 硬件: blog/CS50/PC.md
        - 网络: blog/CS50/inte.md
        - 多媒体: blog/CS50/mult.md
        - 安全: blog/CS50/sec.md
    - MIT-CS198:
        - shell: l1.md


# [Extensions]
plugins:
  - search: 
      lang:
        - en
        - ja
  - tags 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list 
  - toc:
      permalink: true 
  - pymdownx.highlight: 
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences 
  - meta 
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css 
  - mkdocs/css/unordered-list-symbols.css 