# [Info]
site_name: faii-book
site_url: https://faiimea.github.io
site_author: faii
site_description: faii-book

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default 
      primary: indigo 
      accent: orange 
      toggle:
        icon: material/weather-night 
        name: 切换至夜间模式 
    - scheme: slate 
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs 
    - navigation.top 
    - navigation.indexes 
    - navigation.expand 
    - search.suggest 
    - search.highlight 
  language: zh 
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs 
## [top-right corner]
repo_url: https://github.com/faiimea 
repo_name: faii.github 
## [bottom-left corner]
copyright: Copyright &copy; 2022 faii 
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/317064082
      name: Bilibili | falii- 
    - icon: fontawesome/brands/github
      link: https://github.com/faiimea
      name: GitHub | faiimea

# [Navigtion]
nav:
- 关于:
    - ABOUT/index.md 
    - 更新日志: ABOUT/date.md
- ACG:
    - Life/index.md
    - 虚拟主播: 
        - Vtubers: Life/vtubers/vtuber.md
        - 绊爱:  Life/vtubers/kizuno.md
        - 戌亥床:  Life/vtubers/inui.md
    - 动漫: 
        - animes: Life/animes/anime.md
    - 角色: Life/character.md
    - gal: 
        - gals: Life/gals/gal.md #TODO
    # - game: Life/game.md
  
- Use:
    - Step/index.md   
    - 网站: Step/web.md
    - 项目: 
        # - 项目line: Step/projects/project.md
        - faii-map: Step/projects/M.A.P.md


- Blog:
    - blog/index.md
    - CSLIY:
      - HAR-CS50: blog/CSLIY/HAR-CS50.md
      # - MIT-CS198: blog/CSLIY/MIT-CS198.md
      # - MIT-6.042J: blog/CSLIY/MIT-6.042J.md
      - HUJI-NTT: blog/CSLIY/HUJI-NTT.md
      - UCB-CS61A: blog/CSLIY/UCB-CS61A.md
      # - UCB-CS61C: blog/CSLIY/UCB-CS61C.md
      - CMU-CS15_213: blog/CSLIY/CMU-CS15_213.md
      # - leetcode_101: blog/CSLIY/leetcode.md
      - NJU_PA: blog/CSLIY/pa.md
      - D2l: blog/CSLIY/D2l.md
    - NSEC:
      - PDNPulse: blog/NSEC/PDNPulse.md
      - DeHiREC: blog/NSEC/DeHiREC.md
      - respeaker V2: blog/NSEC/putty_lab.md



# [Extensions]
plugins:
  - search: 
      lang:
        - en
        - ja
  - tags 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list 
  - toc:
      permalink: true 
  - pymdownx.highlight: 
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences 
  - meta 
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css 
  - mkdocs/css/unordered-list-symbols.css 